name: Docker Build And Publish

on:
  schedule:
    - cron: "0 1 1 * *" # Run at 01:00 on the 1st of every month
  push:
  workflow_dispatch: # Allow manual triggering of the workflow

env:
  DOCKERHUB_REPOSITORY: "gabriellando/website"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Resolve image tag
        shell: bash
        run: |
          if [[ "${{ gitea.ref }}" == refs/tags/* ]]; then
            tag_name="${{ gitea.ref }}"
            tag_name="${tag_name#refs/tags/}"
          elif [[ "${{ gitea.ref }}" == "refs/heads/main" ]]; then
            tag_name="latest"
          else
            tag_name="dev"
          fi

          echo "TAG_NAME=$tag_name" >> "$GITHUB_ENV"

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TAG_NAME }}"

      # Update Docker Hub description with the README.md content
      # https://github.com/peter-evans/dockerhub-description
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPOSITORY }}
          readme-filepath: ./README.md
